<?php
namespace Polcode\UnitConverterBundle\Tests\Math;

use Polcode\UnitConverterBundle\Math\EvalMath;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-25 at 14:10:33.
 */
class EvalMathTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var FieldCalculate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new EvalMath();
    }

    public function testBasicEvaluate() {
        $this->assertEquals(12, $this->object->evaluate("3+9"));
        $this->assertEquals(21, $this->object->evaluate("(3+9*2)"));
        $this->assertEquals(-21, $this->object->evaluate("-(3+9*2)"));
        $this->assertEquals(-2, $this->object->evaluate("2+2*(-2)"));
    }
    
    public function testEvaluateWithParameter() {
        $this->object->evaluate('x = 2');
        $this->assertEquals(5, $this->object->evaluate("3+x"));
        $this->assertEquals(21, $this->object->evaluate("(3+9*x)"));
        $this->assertEquals(-39, $this->object->evaluate("-(3+9*2x)"));
        $this->assertEquals(10, $this->object->evaluate("2+2*(-2)(-x)"));
    }

}
