<?php

namespace Polcode\UnitConverterBundle\Test\Structures;
use Polcode\UnitConverterBundle\Structures\Unit;
use Polcode\UnitConverterBundle\Structures\UnitCategory;
use Polcode\UnitConverterBundle\ConversionMethod\ConversionByScale;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-24 at 15:24:32.
 */
class UnitTest extends \PHPUnit_Framework_TestCase {

    public function testConstruct() {
        $category = new UnitCategory('length');
        $unit = new Unit('cm', new ConversionByScale(0.01), $category);
        $this->assertEquals('cm', $unit->getSymbol());
        $this->assertEquals(0.01, $unit->getConversionMethod()->calculateValueToStandardUnit(1));
        $this->assertEquals('length', $unit->getCategory()->getName());
    }

    public function testSynonyms() {
        $category = new UnitCategory('legth');
        $unit = new Unit('m', new ConversionByScale(1), $category);
        $unit->addSynonyms(array('meter', 'meters'));
        $unit->addSynonyms(array('sth'));

        $this->assertTrue($unit->hasSynonym('meter'));
        $this->assertTrue($unit->hasSynonym('meters'));
        $this->assertTrue($unit->hasSynonym('sth'));
        $this->assertFalse($unit->hasSynonym('foot'));
    }

}
