<?php

namespace Polcode\UnitConverterBundle\Test\Structures;

use Polcode\UnitConverterBundle\Structures\UnitCategory;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-25 at 09:25:41.
 */
class UnitCategoryTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var UnitCategory
     */
    protected $object;

    protected function setUp() {
        $this->object = new UnitCategory('mass');
    }

    /**
     * @covers Polcode\UnitConverterBundle\Structures\UnitCategory::getName
     */
    public function testGetName() {
        $this->assertEquals('mass', $this->object->getName());
    }

    public function testEqual() {
        $equalObject = new UnitCategory('mass');
        $this->assertTrue($this->object->equal($equalObject));
    }

    public function testEqual_nonEqual() {
        $nonEqualObject = new UnitCategory('length');
        $this->assertFalse($this->object->equal($nonEqualObject));
    }

}
